<a href="https://colab.research.google.com/github/Vovladimir/Numpy_Matplotlib_Scikit-learn/blob/lesson3/%D0%94%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Загрузите датасет Wine из встроенных датасетов sklearn.datasets с помощью функции load_wine в переменную data.


In [60]:
from sklearn.datasets import load_wine

In [61]:
import numpy as np
import pandas as pd


In [62]:
data = load_wine()

Полученный датасет не является датафреймом. Это структура данных, имеющая ключи аналогично словарю. Просмотрите тип данных этой структуры данных и создайте список data_keys, содержащий ее ключи.


In [63]:
type(data)

sklearn.utils.Bunch

In [64]:
data_keys = data.keys()

In [65]:
data_keys

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

Просмотрите данные, описание и названия признаков в датасете. Описание нужно вывести в виде привычного, аккуратно оформленного текста, без обозначений переноса строки, но с самими переносами и т.д.4). Сколько классов содержит целевая переменная датасета? Выве
дите названия классов.


In [66]:
for i in data:
  print(data[i])

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
['class_0' 'class_1' 'class_2']
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric

Содержит 3 класса: class_0, class_1, class_2

На основе данных датасета (они содержатся в двумерном массиве Numpy) и названий признаков создайте датафрейм под названием X.


In [67]:
X = pd.DataFrame(data['data'], columns=data['feature_names'])

In [68]:
X.head()

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

Выясните размер датафрейма X и установите, имеются ли в нем пропущенные значения.


In [69]:
X.shape

(178, 13)

In [70]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

Добавьте в датафрейм поле с классами вин в виде чисел, имеющих тип данных numpy.int64. Название поля - 'target'.


In [71]:
X['target'] = data['target']

In [72]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  targe

 Постройте матрицу корреляций для всех полей X. Дайте полученному датафрейму название X_corr.

In [73]:
X_corr = X.corr()

In [74]:
X_corr

alcohol  malic_acid  ...   proline    target
alcohol                       1.000000    0.094397  ...  0.643720 -0.328222
malic_acid                    0.094397    1.000000  ... -0.192011  0.437776
ash                           0.211545    0.164045  ...  0.223626 -0.049643
alcalinity_of_ash            -0.310235    0.288500  ... -0.440597  0.517859
magnesium                     0.270798   -0.054575  ...  0.393351 -0.209179
total_phenols                 0.289101   -0.335167  ...  0.498115 -0.719163
flavanoids                    0.236815   -0.411007  ...  0.494193 -0.847498
nonflavanoid_phenols         -0.155929    0.292977  ... -0.311385  0.489109
proanthocyanins               0.136698   -0.220746  ...  0.330417 -0.499130
color_intensity               0.546364    0.248985  ...  0.316100  0.265668
hue                          -0.071747   -0.561296  ...  0.236183 -0.617369
od280/od315_of_diluted_wines  0.072343   -0.368710  ...  0.312761 -0.788230
proline                       0.643720   -0.192011  ...  1.000000 -0.633717
target                       -0.328222    0.437776  ... -0.633717  1.000000

[14 rows x 14 columns]

Создайте список high_corr из признаков, корреляция которых с полем target по абсолютному значению превышает 0.5 (причем, само поле target не должно входить в этот список).


In [75]:
abs(X_corr.target) > 0.5

alcohol                         False
malic_acid                      False
ash                             False
alcalinity_of_ash                True
magnesium                       False
total_phenols                    True
flavanoids                       True
nonflavanoid_phenols            False
proanthocyanins                 False
color_intensity                 False
hue                              True
od280/od315_of_diluted_wines     True
proline                          True
target                           True
Name: target, dtype: bool

In [76]:
high_corr = list(X_corr['target'][(abs(X_corr.target) > 0.5) & (X_corr['target'] != 1)].index)

In [77]:
high_corr

['alcalinity_of_ash',
 'total_phenols',
 'flavanoids',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [78]:
X = X.drop(columns=['target'])

In [79]:
X.head()

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [80]:
for i in range(len(high_corr)):
  X[f'{high_corr[i]}_2'] = (X[f'{high_corr[i]}'])**2

In [81]:
X.head()

alcohol  malic_acid   ash  ...   hue_2  od280/od315_of_diluted_wines_2  proline_2
0    14.23        1.71  2.43  ...  1.0816                         15.3664  1134225.0
1    13.20        1.78  2.14  ...  1.1025                         11.5600  1102500.0
2    13.16        2.36  2.67  ...  1.0609                         10.0489  1404225.0
3    14.37        1.95  2.50  ...  0.7396                         11.9025  2190400.0
4    13.24        2.59  2.87  ...  1.0816                          8.5849   540225.0

[5 rows x 19 columns]

In [82]:
X.describe()

alcohol  malic_acid  ...  od280/od315_of_diluted_wines_2     proline_2
count  178.000000  178.000000  ...                      178.000000  1.780000e+02
mean    13.000618    2.336348  ...                        7.322155  6.564591e+05
std      0.811827    1.117146  ...                        3.584316  5.558591e+05
min     11.030000    0.740000  ...                        1.612900  7.728400e+04
25%     12.362500    1.602500  ...                        3.754075  2.505010e+05
50%     13.050000    1.865000  ...                        7.728400  4.536045e+05
75%     13.677500    3.082500  ...                       10.048900  9.702250e+05
max     14.830000    5.800000  ...                       16.000000  2.822400e+06

[8 rows x 19 columns]